name: Download data

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout prod
        uses: actions/checkout@v6
        with:
          ref: gh-pages
          path: prod

      - name: Install requirements
        run: |
          sudo apt-get install -y pandoc
          pip install -r requirements.txt

      - name: Move everything to /w
        run: mv web/* prod

      - name: Download all
        run: |
          python -u downloader.py --all --db prod/db -o prod/d

      - name: Generate OPDS feeds
        run: |
          python generate_opds.py --db prod/db -o prod/opds

      - name: Commit to prod
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          repository: prod
