name: Download data and deploy to Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  main:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install requirements
        run: |
          sudo apt-get install -y pandoc
          pip install -r requirements.txt

      - name: Cache DB
        uses: actions/cache@v4
        with:
          path: db.pickle
          key: db

      - name: Cache data
        uses: actions/cache@v4
        with:
          path: /w/d
          key: data

      - name: Move web to /w
        run: |
          sudo mkdir -m 777 -p /w
          mv web/* /w

      - name: Download all
        run: python downloader.py -o /w/d --all

      - name: Generate index
        run: |
          python /w/generate-index.py -o /w/index.html --db db.pickle
          rm /w/generate-index.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "/w"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
