name: Download data

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install requirements
        run: |
          sudo apt-get install -y pandoc
          pip install -r requirements.txt

      - name: Make cache directories
        run: |
          sudo mkdir -m 1777 -p /w
          mkdir -p /w/d

      - name: Cache DB
        uses: MasterworksIO/action-local-cache@2.1.0
        with:
          path: db
          key: db

      - name: Cache data
        uses: MasterworksIO/action-local-cache@2.1.0
        with:
          path: /w/d
          key: data

      - name: Move everything to /w
        run: mv web/* /w

      - name: Download all
        run: |
          python -u downloader.py -o /w/d --all
          mv db /w

      - name: Trigger "Deploy pages"
        env:
          GH_TOKEN: ${{ secrets.CLASSIC_TOKEN }}
        run: gh workflow run "Deploy pages"
