name: Update DB

on:
  schedule:
    - cron: "12 12 * * 1" # at 12:12 every Monday
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Ensure that gh-pages exists
        uses: mrtnvgr/create-orphan-branch@master
        with:
          branch-name: gh-pages

      - name: Checkout prod
        uses: actions/checkout@v6
        with:
          ref: gh-pages
          path: prod

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Update DB
        run: python -u generate_db.py --db prod/db

      - name: Commit to prod
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          repository: prod

      - name: Trigger "Download data"
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh workflow run "Download data"
